### ISSUE TITLE
Will this package also work with non-persistent data (i.e. make() vs. create())?

### ISSUE THREAD

**Issue by Namoshek** [makeabledk/laravel-factory-enhanced#11]
Simple question: Can this package also create non-persistent models with their relations?

With the normal faker, it currently is a bit of a pain to create such structures in a non-persistent way, because you cannot work with relations properly:
```php
$users = factory(App\User::class, 3)
    ->create()
    ->each(function ($user) {
        $user->setRelation('posts', factory(App\Post::class, 3)->make());
        $user->posts->each(function ($post) use ($user) {
            $post->setRelation('user', $user);
        });
    });
```
_Note: `$user->setRelation('posts', $posts)` because setting it directly via `$user->posts = $posts` will set it as attribute and not as relation._

The reason I ask is that for a lot of my code I don't need persisted models (which is a good thing in regards to testing the code, because it is much faster without a database). But above isn't quite practical in regards of creating test data. Especially when the scenario is not as simple as this one-to-many relationship.

**Comment by rasmuscnielsen** [comment]
Hi @Namoshek 

Actually this is a pretty neat idea which did not come not mind when building it.

Currently using `make` will just factory the models themselves with not further relations.

I'm not currently sure how comprehensive it would be to implement, and at this point it's not on the top of the list. 

I'll keep the issue open for now as a feature request, and keep it in mind for future enhancements. Also I'd be happy to review any suggested implementations, although it would depend greatly on how it fits in with the future plans for the package whether or not it would make it to a release.
