### ISSUE TITLE
Creating additional record on one-to-one relations using `with()` and `factory closure` together 

### ISSUE THREAD

**Issue by rmezhuev** [makeabledk/laravel-factory-enhanced#14]
Case:

Lets say we have `Post` and `Category` one to one relation. Factories will look like

```php
$factory->define(Post::class, function (Faker $faker) {
    return [
        'name' => $faker->name,
        'category_id' => function(){
        	return factory(Category::class);
        },
        'text' => $faker->paragraph 
    ];
});

$factory->define(Category::class, function (Faker $faker) {
    return [
        'name' => $faker->name,
    ];
});

```

  In case if I generate Post like this

```php
$post = factory(Post::class)
  ->with('category', ['name' => 'programming'])
  ->create()
```

I will get correct `Post` with related `programming` category. But as side effect I also get another dummy category generated by post factory. So I end up with two categories instead of one (it can be unexpected in tests). The only way to prevent this is to manually set  ``'category_id'`` to `null` but this is not elegant and requires to remember about all relations and sub-relations

```php
$post = factory(Post::class)
  ->with('category', ['name' => 'programming'])
  ->create(['category_id' => null])
```

I really like the power that `with` provides, but I still want to have default relation generation using factory closures. 

Can you help with the way to use `with()` alongside with `factory closures` without side effects?

**Comment by rasmuscnielsen** [comment]
Hi @rmezhuev 

In general I never find myself in need for factory'ing other models in their factory definition anymore. I would always prefer to do it explicitly in my tests with `factory(Post::class)->with('category')->create()`.

This allows me to have fine-grained control over which relations I actually need for the test, and prevents making more queries than absolutely necessary. 

On the `master` branch of this package we have also introduced `presets` which allow you to define more complicated and reusable setups upfront. Maybe you would find this applicable to your use case. 
For more documentation see: https://github.com/laravel/framework/pull/29592#pullrequestreview-302110441

Unless this package's behavior differ from the Laravel core factory in terms of this issue (does the core factory create 2 models in the example above?), then I wouldn't go out of my way to change any creation-logic at this moment.
