### ISSUE TITLE
Use with fakerphp/faker

### ISSUE THREAD

**Issue by jaulz** [makeabledk/laravel-factory-enhanced#40]
Is it also somehow possible to use this library with `fakerphp/faker`? Currently, `fakerphp/faker` conflicts with `fzaninotto/faker` and thus I cannot install this library. 

P.S.: even with a fork of this repository it seems it doesn't run well with Laravel 8 😞

**Comment by rasmuscnielsen** [comment]
Hey @jaulz 

Really sorry for the lack of response. Unfortunately somehow your issue slipped passed my attention, as well as less time for the maintenance of our 20+ Laravel packages. 

I've just pushed an update that only uses Faker in require-dev, as well as upgraded to the fakerphp version. 

As for the Laravel-8 support, you (or the another person reading this) might want to have at look at the branches:

- `next` supports Laravel 8 and uses the new class based factories
- `feat/v3` supports Laravel 8, but maintains older Laravel syntax

The branches are fully developed, but awaits proper updated documentation which unfortunately is what has kept them from being tagged and released at this point.
